import type { Node as ProseMirrorNode, Schema } from 'prosemirror-model'

import {
  buildModeSwitchDocumentIdentity,
  pmRootInnerSize,
  type ModeSwitchDocumentIdentity,
} from './modeSwitchDocumentProjection'
import type { HierarchicalSelectionCore } from './modeSwitchSelectionCore'
import { getOutlineParseSchema } from './markdownOutlineFromMarkdown'
import { modeSwitchPlainTextFingerprint } from './modeSwitchFingerprint'
import { assertFrozenKernelContract } from './modeSwitchFrozenKernelContract'
import { ModeSwitchFreezeError } from './modeSwitchFreezeFailure'
import { assertProjectionPurity, computeSelection } from './modeSwitchProjection'
import { deriveHierarchicalFromCmSelection } from './modeSwitchSemanticProjection'
import { buildFrozenStructuralIR, type FrozenStructuralIR } from './modeSwitchStructuralIR'
import { canonicalMarkdownSemantics } from '../markdown/canonicalMarkdownSemantics'

export type { ModeSwitchDocumentIdentity } from './modeSwitchDocumentProjection'

/**
 * Identical to `ModeSwitchHierarchicalPayload`; snapshot module does not depend on `viewportModeAnchor`.
 */
export type FrozenModeSwitchHierarchical = {
  readonly bufferHash: string
  readonly anchor: HierarchicalSelectionCore
  readonly head: HierarchicalSelectionCore
}

/**
 * Single ⌘/ Freeze object: `canonicalBuffer` **Only** generated by PM serialization once within this module freeze.
 */
export type ModeSwitchSnapshot = {
  readonly captureFrameId: number
  readonly documentKey: string
  readonly canonicalBuffer: string
  readonly documentIdentity: ModeSwitchDocumentIdentity
  /** The only frozen geometry row table (with `semanticExtent`); projection only reads this table.*/
  readonly frozenStructuralIR: FrozenStructuralIR
  readonly hierarchical: FrozenModeSwitchHierarchical | null
  readonly selection: { readonly anchor: number; readonly head: number }
  readonly expectedPmAnchor: number
  readonly expectedPmHead: number
  readonly sourceMode: 'visual' | 'source'
}

function freezeHierarchical(h: FrozenModeSwitchHierarchical): FrozenModeSwitchHierarchical {
  return Object.freeze({
    bufferHash: h.bufferHash,
    anchor: Object.freeze({ ...h.anchor }),
    head: Object.freeze({ ...h.head }),
  })
}

function withCanonicalBufferHash(
  hierarchical: FrozenModeSwitchHierarchical | null,
  canonicalBuffer: string,
): FrozenModeSwitchHierarchical | null {
  if (!hierarchical) return null
  const bufferHash = modeSwitchPlainTextFingerprint(canonicalBuffer)
  return freezeHierarchical({
    ...hierarchical,
    bufferHash,
  })
}

/** DEV: Freeze PM/CM coordinates must be writable in `TextSelection` / CM selection (if illegal, throw).*/
function assertFrozenProjectionCoordsDev(args: {
  hierarchical: FrozenModeSwitchHierarchical | null
  coords: { pmAnchor: number; pmHead: number; cmAnchor: number; cmHead: number }
  pmInnerMax: number
  canonicalLen: number
}): void {
  if (!import.meta.env.DEV) return
  const { coords, pmInnerMax, canonicalLen, hierarchical } = args
  const fail = (msg: string) => {
    throw new ModeSwitchFreezeError(`[mode-switch] ${msg}`, {
      reason: 'frozen_projection_coords',
      message: msg,
      coords,
      pmInnerMax,
      canonicalLen,
      hierarchical,
    })
  }
  if (
    !Number.isFinite(coords.pmAnchor) ||
    !Number.isFinite(coords.pmHead) ||
    !Number.isFinite(coords.cmAnchor) ||
    !Number.isFinite(coords.cmHead)
  ) {
    fail('non-finite projection coords')
  }
  if (coords.cmAnchor < 0 || coords.cmHead < 0 || coords.cmAnchor > canonicalLen || coords.cmHead > canonicalLen) {
    fail('cm coords out of canonical buffer range')
  }
  if (pmInnerMax < 1) {
    return
  }
  if (coords.pmAnchor < 1 || coords.pmHead < 1 || coords.pmAnchor > pmInnerMax || coords.pmHead > pmInnerMax) {
    fail('pm coords out of pmRootInnerSize range')
  }
}

/**
 * Synchronous, single-read path: **only** `canonicalBuffer` and `frozenStructuralIR` are generated here.
 */
export function freezeModeSwitchSnapshot(args: {
  captureFrameId: number
  documentKey: string
  hierarchical: FrozenModeSwitchHierarchical | null
  doc: ProseMirrorNode
  schema: Schema
  sourceMode: 'visual' | 'source'
  cmSelectionOverride?: { anchor: number; head: number }
  /** Source code true value: used for CM and selection mapping, prohibiting PM serialize from introducing \\ escape*/
  identityMarkdown?: string
}): ModeSwitchSnapshot {
  const canonicalBuffer =
    args.identityMarkdown ?? canonicalMarkdownSemantics.serializeForModeBridge(args.doc, args.schema)
  const hierarchical = withCanonicalBufferHash(args.hierarchical, canonicalBuffer)
  const frozenStructuralIR = buildFrozenStructuralIR({ canonicalBuffer, hierarchical, doc: args.doc })
  const pmInner = pmRootInnerSize(args.doc)
  const coords = computeSelection(hierarchical, frozenStructuralIR, canonicalBuffer, pmInner)
  assertFrozenProjectionCoordsDev({
    hierarchical,
    coords,
    pmInnerMax: pmInner,
    canonicalLen: canonicalBuffer.length,
  })
  const selection = args.cmSelectionOverride
    ? Object.freeze({ ...args.cmSelectionOverride })
    : Object.freeze({ anchor: coords.cmAnchor, head: coords.cmHead })
  const documentIdentity = buildModeSwitchDocumentIdentity(canonicalBuffer, args.doc)

  const snap = Object.freeze({
    captureFrameId: args.captureFrameId,
    documentKey: args.documentKey,
    canonicalBuffer,
    documentIdentity,
    frozenStructuralIR,
    hierarchical,
    selection,
    expectedPmAnchor: coords.pmAnchor,
    expectedPmHead: coords.pmHead,
    sourceMode: args.sourceMode,
  })
  if (import.meta.env.DEV) {
    assertFrozenKernelContract({ frozenStructuralIR })
    assertProjectionPurity(frozenStructuralIR, canonicalBuffer)
  }
  return snap
}

/**
 * Return to WYSIWYG from the source code: After parsing the CM text into PM `doc`, canonical and frozen IR are generated through `freezeModeSwitchSnapshot` only.
 */
export function freezeReturningToVisualSnapshot(
  visualExitSnapshot: ModeSwitchSnapshot,
  sourceRead: { markdown: string; anchor: number; head: number },
): ModeSwitchSnapshot {
  const schema = getOutlineParseSchema()
  const doc = canonicalMarkdownSemantics.parse(sourceRead.markdown, schema)
  const canonicalBuffer = sourceRead.markdown
  const frozenStructuralIR = buildFrozenStructuralIR({
    canonicalBuffer,
    hierarchical: visualExitSnapshot.hierarchical,
    doc,
  })
  const cmHierarchical = deriveHierarchicalFromCmSelection(
    sourceRead.anchor,
    sourceRead.head,
    frozenStructuralIR,
  )
  return freezeModeSwitchSnapshot({
    captureFrameId: visualExitSnapshot.captureFrameId,
    documentKey: visualExitSnapshot.documentKey,
    hierarchical: {
      bufferHash: '',
      anchor: cmHierarchical.anchor,
      head: cmHierarchical.head,
    },
    doc,
    schema,
    sourceMode: 'source',
    cmSelectionOverride: { anchor: sourceRead.anchor, head: sourceRead.head },
    identityMarkdown: sourceRead.markdown,
  })
}
