#!/usr/bin/env python3
"""
Generate Rust `menu_manifest.rs` from the menu.compile manifest (CI + runtime fail-fast).

Run: python3 scripts/export_menu_rust_manifest.py
"""
from __future__ import annotations

import pathlib
import re
import sys

_SCRIPTS = pathlib.Path(__file__).resolve().parent
_LIB = _SCRIPTS.parent / "lib"
if str(_LIB) not in sys.path:
    sys.path.insert(0, str(_LIB))

from locale_contract import zh_cn_edit_p0_shell_expected  # noqa: E402

ROOT = pathlib.Path(__file__).resolve().parents[2]
COMPILE_TS = ROOT / "src" / "menu" / "menu.compile.ts"
APP_MENU_RS = ROOT / "src-tauri" / "src" / "app_menu.rs"
OUT = ROOT / "src-tauri" / "src" / "menu_manifest.rs"

MENU_ITEM_ID_RE = re.compile(
    r"""menu_item\s*\(\s*&menu_handle\s*,\s*"([^"]+)"\s*,""",
)

EDIT_P0_RE = re.compile(
    r"actionId:\s*'([^']+)'",
)


def rust_ids_from_app_menu() -> list[str]:
    return sorted(set(MENU_ITEM_ID_RE.findall(APP_MENU_RS.read_text(encoding="utf-8"))))


def edit_p0_from_compile() -> list[tuple[str, str, str]]:
    text = COMPILE_TS.read_text(encoding="utf-8")
    block = re.search(
        r"export const RUST_EDIT_MENU_P0.*?=\s*\[(.*?)\]\s*as const",
        text,
        re.DOTALL,
    )
    if not block:
        return []
    rows: list[tuple[str, str, str]] = []
    ids = re.findall(r"actionId:\s*'([^']+)'", block.group(1))
    keys = re.findall(r"labelKey:\s*'([^']+)'", block.group(1))
    shells = re.findall(r"shellKey:\s*'([^']+)'", block.group(1))
    for i, aid in enumerate(ids):
        rows.append((aid, keys[i] if i < len(keys) else "", shells[i] if i < len(shells) else ""))
    return rows


def main() -> int:
    if not APP_MENU_RS.is_file() or not COMPILE_TS.is_file():
        print("missing sources", file=sys.stderr)
        return 1

    rust_ids = rust_ids_from_app_menu()
    edit_p0 = edit_p0_from_compile()

    lines = [
        "// @generated by scripts/export_menu_rust_manifest.py — do not edit",
        "",
        "/// Top-bar menu_item action ids (empty when menus are React-only in the webview)",
        "pub const REQUIRED_MENU_ACTION_IDS: &[&str] = &[",
    ]
    for rid in rust_ids:
        lines.append(f'  "{rid}",')
    lines.append("];")
    lines.append("")
    lines.append("/// Edit P0: zh-CN runtime contract (shell field name, expected value)")
    lines.append("pub const ZH_CN_EDIT_P0_CONTRACT: &[(&str, &str)] = &[")
    zh_expected = zh_cn_edit_p0_shell_expected()
    for _aid, _lk, sk in edit_p0:
        if sk in zh_expected:
            lines.append(f'  ("{sk}", "{zh_expected[sk]}"),')
    lines.append("];")
    lines.append("")

    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT} ({len(rust_ids)} action ids, {len(zh_expected)} zh-CN edit P0)")
    return 0


if __name__ == "__main__":
    import sys

    raise SystemExit(main())
