#!/usr/bin/env python3
"""
Verify menu-domain React UI ↔ Rust shell alignment; zh-CN must not expose en fallback as menu copy.

Dependencies:
  - scripts/menu_canonical.json (generated by export_menu_canonical.py)
  - scripts/shell_menu_to_ui_key.py

Run: python3 scripts/export_menu_canonical.py && python3 scripts/validate_menu_i18n_sync.py
"""
from __future__ import annotations

import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
CANONICAL = ROOT / "scripts" / "locale" / "menu_canonical.json"
UI_EN = ROOT / "src" / "i18n" / "locales" / "en.json"
UI_ZH = ROOT / "src" / "i18n" / "locales" / "zh-CN.json"
SHELL_EN = ROOT / "src-tauri" / "i18n" / "en.json"
SHELL_ZH = ROOT / "src-tauri" / "i18n" / "zh-CN.json"

_SCRIPTS = pathlib.Path(__file__).resolve().parent
if str(_SCRIPTS) not in sys.path:
    sys.path.insert(0, str(_SCRIPTS))

from shell_menu_to_ui_key import build_map  # noqa: E402

P0_PREFIXES = ("menu.edit.", "menu.file.", "menu.view.")


def load_json(path: pathlib.Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def merge_ui(en: dict[str, str], loc: dict[str, str]) -> dict[str, str]:
    out = dict(en)
    for k, v in loc.items():
        if isinstance(k, str) and isinstance(v, str) and not k.startswith("meta."):
            out[k] = v
    return out


def shell_key_for_ui(ui_key: str, ui_to_shell: dict[str, str]) -> str | None:
    return ui_to_shell.get(ui_key)


def main() -> int:
    if not CANONICAL.is_file():
        print("run export_menu_canonical.py first", file=sys.stderr)
        return 1

    canonical = load_json(CANONICAL)
    entries = canonical.get("entries", [])
    if not isinstance(entries, list):
        print("bad menu_canonical.json", file=sys.stderr)
        return 1

    en_ui = {k: v for k, v in load_json(UI_EN).items() if isinstance(k, str) and isinstance(v, str)}
    zh_raw = {k: v for k, v in load_json(UI_ZH).items() if isinstance(k, str) and isinstance(v, str)}
    zh_ui = merge_ui(en_ui, zh_raw)

    shell_en_menu = load_json(SHELL_EN)["menu"]
    shell_zh_menu = load_json(SHELL_ZH)["menu"]
    ui_to_shell = {v: k for k, v in build_map().items()}

    errors: list[str] = []
    checked_p0 = 0

    for ent in entries:
        if not isinstance(ent, dict):
            continue
        ui_key = ent.get("labelKey")
        if not isinstance(ui_key, str) or not ui_key.startswith("menu."):
            continue
        is_p0 = ui_key.startswith(P0_PREFIXES)
        if not is_p0:
            continue
        checked_p0 += 1

        if ui_key not in en_ui:
            errors.append(f"UI en missing key: {ui_key}")
            continue

        sk = shell_key_for_ui(ui_key, ui_to_shell)
        if sk is None:
            #Only a subset of shell native top bars must be in shell JSON; the rest can be UI only
            shell_only_optional = ui_key.startswith(("menu.edit.",)) and ui_key in {
                "menu.edit.copyPlain",
                "menu.edit.copyMd",
                "menu.edit.copyHtml",
                "menu.edit.pastePlain",
                "menu.edit.select",
                "menu.edit.selectBlock",
                "menu.edit.delete",
                "menu.edit.deleteRange",
                "menu.edit.deleteBlock",
                "menu.edit.deleteLine",
                "menu.edit.eol",
                "menu.edit.eol.crlf",
                "menu.edit.eol.lf",
                "menu.edit.space",
                "menu.edit.indentFirst",
                "menu.edit.showBr",
                "menu.edit.emoji",
            }
            if not shell_only_optional and ui_key.startswith("menu.edit."):
                errors.append(f"shell map missing for UI key: {ui_key}")
            continue

        if sk not in shell_en_menu:
            errors.append(f"shell en.json menu missing: {sk} (ui {ui_key})")
        if sk not in shell_zh_menu:
            errors.append(f"shell zh-CN.json menu missing: {sk} (ui {ui_key})")

        en_val = en_ui[ui_key]
        zh_val = zh_ui.get(ui_key, "")
        if ui_key not in zh_raw:
            errors.append(f"zh-CN sparse missing: {ui_key}")
        elif zh_val == en_val:
            errors.append(f"zh-CN en-fallback for menu: {ui_key} (= {en_val!r})")

        if sk and sk in shell_zh_menu and sk in shell_en_menu:
            if shell_zh_menu[sk] == shell_en_menu[sk]:
                errors.append(f"shell zh-CN en-fallback: {sk} (= {shell_en_menu[sk]!r})")

    if errors:
        print("menu i18n sync errors:", file=sys.stderr)
        for e in errors:
            print(f"  - {e}", file=sys.stderr)
        return 1

    print(f"OK: validated {checked_p0} P0 menu.* keys (edit/file/view)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
