import type { SemanticIconName } from '../../design-system/icons'

/** Lucide icon file stem (`lucide-react/dist/esm/icons/<stem>.mjs`) for each semantic menu icon.
 *  Single source of truth — consumed by scripts/export_mac_menu_icons.mjs. */
export const MAC_MENU_SEMANTIC_LUCIDE_STEM: Partial<Record<SemanticIconName, string>> = {
  workspace: 'folder',
  'workspace-open': 'folder-open',
  'workspace-tree': 'folder-tree',
  note: 'file-text',
  'note-new': 'file-plus',
  graph: 'network',
  backlinks: 'corner-down-left',
  assets: 'paperclip',
  tags: 'tag',
  frontmatter: 'file-braces',
  embeds: 'paperclip',
  search: 'search',
  settings: 'settings',
  appearance: 'palette',
  export: 'download',
  editor: 'pen-line',
  language: 'languages',
  shortcuts: 'keyboard',
  source: 'braces',
  preview: 'book-open',
  focus: 'focus',
  'sidebar-close': 'panel-left-close',
  'sidebar-open': 'panel-left-open',
  outline: 'list-tree',
  list: 'list',
  close: 'x',
  refresh: 'refresh-cw',
  'sort-az': 'arrow-down-a-z',
  'sort-za': 'arrow-up-a-z',
  'sort-time': 'clock-3',
  'sort-created': 'calendar-days',
  callout: 'message-square',
  'callout-note': 'sticky-note',
  'callout-tip': 'lightbulb',
  'callout-success': 'circle-check',
  'callout-important': 'badge-check',
  'callout-warning': 'triangle-alert',
  'callout-caution': 'octagon-alert',
  'callout-danger': 'shield-alert',
  'callout-info': 'info',
  snapshot: 'camera',
  privacy: 'shield',
  save: 'save',
  print: 'printer',
  delete: 'trash-2',
  undo: 'undo-2',
  redo: 'redo-2',
  cut: 'scissors',
  copy: 'copy',
  paste: 'clipboard-paste',
  window: 'app-window',
  'tab-new': 'square-plus',
  import: 'upload',
  rename: 'pen-line',
  reveal: 'locate-fixed',
  'zoom-in': 'zoom-in',
  'zoom-out': 'zoom-out',
  fullscreen: 'maximize',
  'word-count': 'whole-word',
  table: 'table',
  code: 'code',
  math: 'calculator',
  quote: 'quote',
  'list-ordered': 'list-ordered',
  task: 'square-check-big',
  image: 'image',
  heading: 'heading',
  history: 'history',
  hr: 'minus',
  footnote: 'superscript',
  emoji: 'smile',
  template: 'layout-template',
  help: 'book-open',
  'help-circle': 'circle-question-mark',
  find: 'search',
  link: 'link-2',
  'text-underline': 'underline',
  'text-highlight': 'highlighter',
  minimize: 'minimize-2',
  tile: 'maximize',
}

/** Semantic icons referenced by macOS menu mappings (for asset export). */
export function listMacMenuSemanticIconNames(): SemanticIconName[] {
  return Object.keys(MAC_MENU_SEMANTIC_LUCIDE_STEM) as SemanticIconName[]
}
