import type { MenuBarStructureGroup, MenuTreeNode, ToolbarLayout } from './commandManifest.types'

const S = (): MenuTreeNode => ({ kind: 'separator' })
const C = (id: string): MenuTreeNode => ({ kind: 'command', id })
const sub = (id: string, labelKey: string, children: MenuTreeNode[]): MenuTreeNode => ({
  kind: 'submenu',
  id,
  labelKey,
  children,
})

const fmtImageZoom: MenuTreeNode[] = [
  C('fmt-image-zoom-25'),
  C('fmt-image-zoom-33'),
  C('fmt-image-zoom-50'),
  C('fmt-image-zoom-60'),
  C('fmt-image-zoom-80'),
  S(),
  C('fmt-image-zoom-100'),
  S(),
  C('fmt-image-zoom-120'),
  C('fmt-image-zoom-150'),
]

/** Top bar menu tree: only command id + submenu structure, no label/icon/shortcut*/
export const MENU_BAR_STRUCTURE: readonly MenuBarStructureGroup[] = [
  {
    id: 'bar-file',
    labelKey: 'menu.file',
    children: [
      C('file-new'),
      C('file-new-tab'),
      C('file-new-window'),
      S(),
      sub('sub-open', 'menu.file.open', [C('file-open-file'), C('open-folder')]),
      C('file-recent-placeholder'),
      S(),
      C('file-close-workspace'),
      S(),
      C('file-show-intro'),
      C('file-reveal'),
      S(),
      C('file-delete'),
      S(),
      C('file-close'),
      S(),
      C('save'),
      C('file-save-as'),
      C('file-copy-path'),
      C('file-rename'),
      S(),
      C('file-revert'),
      C('file-save-all'),
      S(),
      C('file-import'),
      sub('sub-export', 'menu.file.export', [
        C('file-export-pdf'),
        C('file-export-html'),
        C('file-export-html-plain'),
        C('file-export-image'),
        S(),
        C('file-export-word'),
      ]),
      S(),
      C('preferences'),
      C('file-print'),
    ],
  },
  {
    id: 'bar-edit',
    labelKey: 'menu.edit',
    children: [
      C('edit-undo'),
      C('edit-redo'),
      S(),
      C('edit-cut'),
      C('edit-copy'),
      C('edit-paste'),
      S(),
      C('edit-copy-plain'),
      C('edit-copy-md'),
      C('edit-copy-html'),
      S(),
      C('edit-paste-plain'),
      S(),
      sub('sub-edit-select', 'menu.edit.select', [C('edit-select-all'), C('edit-select-block')]),
      S(),
      C('edit-delete'),
      sub('sub-edit-del-range', 'menu.edit.deleteRange', [C('edit-delete-block'), C('edit-delete-line')]),
      S(),
      sub('sub-edit-eol', 'menu.edit.eol', [C('edit-eol-crlf'), C('edit-eol-lf')]),
      sub('sub-edit-space', 'menu.edit.space', [C('edit-indent-first-line'), C('edit-show-br')]),
      S(),
      sub('sub-edit-find', 'menu.edit.find', [
        C('edit-find'),
        C('edit-find-prev'),
        C('edit-find-next'),
        S(),
        C('edit-find-replace'),
        C('edit-replace-next'),
        S(),
        C('edit-jump-to-selection'),
      ]),
      S(),
      C('edit-emoji'),
    ],
  },
  {
    id: 'bar-paragraph',
    labelKey: 'menu.paragraph',
    children: [
      C('para-h1'),
      C('para-h2'),
      C('para-h3'),
      C('para-h4'),
      C('para-h5'),
      C('para-h6'),
      S(),
      C('para-paragraph'),
      S(),
      C('para-heading-up'),
      C('para-heading-down'),
      S(),
      sub('sub-para-table', 'menu.para.table', [
        C('para-table-insert'),
        S(),
        C('para-table-row-above'),
        C('para-table-row-below'),
      ]),
      C('para-math-block'),
      C('para-insert-code-block'),
      sub('sub-para-code-tools', 'menu.para.codeTools', [
        C('para-code-copy'),
        C('para-code-tools-indent-selection'),
        C('para-code-tools-indent-block'),
      ]),
      sub('sub-para-callout', 'menu.para.callout', [
        C('para-callout-tip'),
        C('para-callout-suggestion'),
        C('para-callout-important'),
        C('para-callout-warning'),
        C('para-callout-caution'),
      ]),
      S(),
      C('para-quote'),
      S(),
      C('para-ol'),
      C('para-ul'),
      C('para-task'),
      sub('sub-para-task', 'menu.para.taskState', [C('para-task-done'), C('para-task-undone')]),
      sub('sub-para-list-indent', 'menu.para.listIndent', [
        C('para-list-indent-more'),
        C('para-list-indent-less'),
      ]),
      S(),
      C('para-insert-paragraph-above'),
      C('para-insert-paragraph-below'),
      S(),
      C('para-link-ref'),
      C('para-footnote'),
      S(),
      C('para-hr'),
      C('para-toc'),
    ],
  },
  {
    id: 'bar-format',
    labelKey: 'menu.format',
    children: [
      C('fmt-bold'),
      C('fmt-italic'),
      C('fmt-underline'),
      C('fmt-inline-code'),
      S(),
      C('fmt-inline-math'),
      C('fmt-strike'),
      C('fmt-comment'),
      S(),
      C('fmt-link'),
      sub('sub-fmt-link-ops', 'menu.fmt.linkOps', [C('fmt-link-open'), C('fmt-link-copy')]),
      sub('sub-fmt-image', 'menu.fmt.image', [
        C('fmt-image'),
        C('fmt-image-insert-local'),
        S(),
        C('fmt-image-reveal'),
        sub('sub-fmt-image-zoom', 'menu.fmt.image.scale', fmtImageZoom),
        sub('sub-fmt-image-conv', 'menu.fmt.image.conv', [C('fmt-image-as-html'), C('fmt-image-as-md')]),
        S(),
        C('fmt-image-delete'),
        S(),
        C('fmt-image-copy-to'),
        C('fmt-image-rename'),
        C('fmt-image-upload'),
        S(),
        C('fmt-image-copy-all'),
        C('fmt-image-move-all'),
        C('fmt-image-upload-all-local'),
        S(),
        C('fmt-image-reload-all'),
        S(),
        sub('sub-fmt-image-on-insert', 'menu.fmt.image.onInsert', [
          C('fmt-image-on-insert-copy'),
          C('fmt-image-on-insert-upload'),
        ]),
        C('fmt-image-root-dir'),
        C('fmt-image-global-settings'),
      ]),
      S(),
      C('fmt-clear-style'),
    ],
  },
  {
    id: 'bar-view',
    labelKey: 'menu.view',
    children: [
      C('toggle-source-mode'),
      S(),
      C('toggle-focus'),
      S(),
      C('toggle-sidebar'),
      C('view-sidebar-outline'),
      C('view-sidebar-files'),
      C('view-search'),
      S(),
      C('view-word-count'),
      S(),
      C('view-zoom-in'),
      C('view-zoom-out'),
      S(),
      C('view-fullscreen'),
      C('view-live-preview'),
    ],
  },
  {
    id: 'bar-window',
    labelKey: 'menu.window',
    children: [
      C('win-minimize'),
      C('win-zoom'),
      S(),
      sub('sub-win-move', 'menu.win.move', [
        sub('sub-win-half', 'menu.win.half', [
          C('win-move-resize-half-left'),
          C('win-move-resize-half-right'),
          C('win-move-resize-half-top'),
          C('win-move-resize-half-bottom'),
        ]),
      ]),
      C('win-tile-full'),
    ],
  },
  {
    id: 'bar-help',
    labelKey: 'menu.native.help',
    children: [
      C('help-about'),
    ],
  },
]

/** toolbar slot → command id list*/
export const TOOLBAR_LAYOUT: ToolbarLayout = {
  'sidebar-header': ['open-folder', 'toggle-source-mode'],
  'editor-format': ['fmt-bold', 'fmt-italic', 'fmt-underline', 'fmt-inline-code', 'fmt-strike', 'fmt-link'],
}
