import type { SemanticIconName } from '../design-system/icons'

/** Lucide icons for top-bar menu commands (text glyphs in manifest take precedence when present). */
export const MENU_COMMAND_SEMANTIC_ICONS: Partial<Record<string, SemanticIconName>> = {
  'file-new': 'note-new',
  'file-new-tab': 'tab-new',
  'file-new-window': 'window',
  'file-new-from-template': 'template',
  'daily-note-open': 'sort-created',
  'daily-note-open-yesterday': 'sort-time',
  'daily-note-open-tomorrow': 'sort-created',
  'template-edit-default': 'note',
  'template-edit-daily': 'sort-created',
  'template-open-folder': 'workspace',
  'template-preferences': 'settings',
  'file-open-file': 'note',
  'open-folder': 'workspace-open',
  'file-close-workspace': 'workspace',
  'file-show-intro': 'preview',
  'file-reveal': 'reveal',
  'file-delete': 'delete',
  'file-close': 'close',
  save: 'save',
  'file-save-as': 'save',
  'file-copy-path': 'copy',
  'file-rename': 'rename',
  'file-history-open': 'history',
  'file-history-create-snapshot': 'snapshot',
  'file-revert': 'refresh',
  'file-save-all': 'save',
  'file-import': 'import',
  'file-export-pdf': 'export',
  'file-export-markdown': 'export',
  'file-export-html': 'export',
  'file-export-html-plain': 'export',
  'file-export-image': 'image',
  'file-export-word': 'export',
  preferences: 'settings',
  'file-print': 'print',

  'edit-copy-plain': 'copy',
  'edit-copy-md': 'copy',
  'edit-copy-html': 'copy',
  'edit-paste-plain': 'paste',
  'edit-select-all': 'editor',
  'edit-select-block': 'editor',
  'edit-delete': 'delete',
  'edit-delete-block': 'delete',
  'edit-delete-line': 'delete',
  'edit-eol-crlf': 'code',
  'edit-eol-lf': 'code',
  'edit-indent-first-line': 'editor',
  'edit-show-br': 'code',
  'edit-find': 'find',
  'edit-find-prev': 'find',
  'edit-find-next': 'find',
  'edit-find-replace': 'find',
  'edit-replace-next': 'find',
  'edit-jump-to-selection': 'find',
  'edit-emoji': 'emoji',

  'para-paragraph': 'heading',
  'para-heading-up': 'heading',
  'para-heading-down': 'heading',
  'para-table-insert': 'table',
  'para-table-row-above': 'table',
  'para-table-row-below': 'table',
  'para-math-block': 'math',
  'para-insert-code-block': 'code',
  'para-code-copy': 'copy',
  'para-code-tools-indent-selection': 'code',
  'para-code-tools-indent-block': 'code',
  'para-callout-tip': 'callout-tip',
  'para-callout-suggestion': 'callout-info',
  'para-callout-important': 'callout-important',
  'para-callout-warning': 'callout-warning',
  'para-callout-caution': 'callout-caution',
  'toolbar-callout': 'callout',
  'para-ol': 'list-ordered',
  'para-ul': 'list',
  'para-task': 'task',
  'para-task-done': 'task',
  'para-task-undone': 'task',
  'para-list-indent-more': 'list',
  'para-list-indent-less': 'list',
  'para-insert-paragraph-above': 'editor',
  'para-insert-paragraph-below': 'editor',
  'para-link-ref': 'link',
  'para-footnote': 'footnote',
  'para-hr': 'hr',
  'para-toc': 'outline',

  'fmt-underline': 'text-underline',
  'fmt-inline-math': 'math',
  'fmt-comment': 'editor',
  'fmt-link': 'link',
  'fmt-link-open': 'link',
  'fmt-link-copy': 'copy',
  'fmt-image': 'image',
  'fmt-image-insert-local': 'image',
  'fmt-image-reveal': 'reveal',
  'fmt-image-zoom-25': 'zoom-out',
  'fmt-image-zoom-33': 'zoom-out',
  'fmt-image-zoom-50': 'zoom-out',
  'fmt-image-zoom-60': 'zoom-out',
  'fmt-image-zoom-80': 'zoom-out',
  'fmt-image-zoom-100': 'image',
  'fmt-image-zoom-120': 'zoom-in',
  'fmt-image-zoom-150': 'zoom-in',
  'fmt-image-as-html': 'code',
  'fmt-image-as-md': 'note',
  'fmt-image-delete': 'delete',
  'fmt-image-copy-to': 'copy',
  'fmt-image-rename': 'rename',
  'fmt-image-upload': 'import',
  'fmt-image-copy-all': 'copy',
  'fmt-image-move-all': 'import',
  'fmt-image-upload-all-local': 'import',
  'fmt-image-reload-all': 'refresh',
  'fmt-image-on-insert-copy': 'copy',
  'fmt-image-on-insert-upload': 'import',
  'fmt-image-root-dir': 'workspace',
  'fmt-image-global-settings': 'settings',
  'fmt-clear-style': 'refresh',

  'toggle-source-mode': 'source',
  'toggle-focus': 'focus',
  'toggle-sidebar': 'sidebar-open',
  'view-sidebar-outline': 'outline',
  'view-sidebar-files': 'files',
  'view-search': 'search',
  'view-word-count': 'word-count',
  'view-zoom-in': 'zoom-in',
  'view-zoom-out': 'zoom-out',
  'view-fullscreen': 'fullscreen',
  'view-live-preview': 'preview',

  'win-minimize': 'minimize',
  'win-zoom': 'window',
  'win-move-resize-half-left': 'tile',
  'win-move-resize-half-right': 'tile',
  'win-move-resize-half-top': 'tile',
  'win-move-resize-half-bottom': 'tile',
  'win-tile-full': 'fullscreen',

  'help-shortcuts': 'shortcuts',
  'help-about': 'app-mark',
  'help-privacy': 'privacy',
  'help-website': 'link',
  'help-feedback': 'editor',
}

export const MENU_SUBMENU_SEMANTIC_ICONS: Partial<Record<string, SemanticIconName>> = {
  'sub-templates': 'template',
  'sub-open': 'workspace-open',
  'sub-file-history': 'history',
  'sub-export': 'export',
  'sub-edit-select': 'editor',
  'sub-edit-del-range': 'delete',
  'sub-edit-eol': 'code',
  'sub-edit-space': 'editor',
  'sub-edit-find': 'find',
  'sub-para-table': 'table',
  'sub-para-code-tools': 'code',
  'sub-para-callout': 'callout',
  'sub-para-task': 'task',
  'sub-para-list-indent': 'list',
  'sub-fmt-link-ops': 'link',
  'sub-fmt-image': 'image',
  'sub-fmt-image-zoom': 'zoom-in',
  'sub-fmt-image-conv': 'refresh',
  'sub-fmt-image-on-insert': 'import',
  'sub-fmt-text-color': 'appearance',
  'sub-win-move': 'window',
  'sub-win-half': 'tile',
  'sub-recent-dynamic': 'sort-time',
}

export function resolveMenuCommandSemanticIcon(commandId: string): SemanticIconName | undefined {
  return MENU_COMMAND_SEMANTIC_ICONS[commandId]
}

export function resolveMenuSubmenuSemanticIcon(submenuId: string): SemanticIconName | undefined {
  return MENU_SUBMENU_SEMANTIC_ICONS[submenuId]
}
