/**
 * UI `menu.*` labelKey ↔ Tauri shell `menu.<snake>` key mapping (aligned with `scripts/shell_menu_to_ui_key.py`).
 * The Menu SSOT structure is in `menu.schema.ts`; this file is only responsible for shell copy key name compilation.
 */

/** shell `menu` segment keys → UI `menu.*` keys (consistent with Python SHELL_UI_KEY_OVERRIDES + infer)*/
export const SHELL_TO_UI_LABEL_KEY: Record<string, string> = {
  edit_bar: 'menu.edit',
  edit_undo: 'menu.edit.undo',
  edit_redo: 'menu.edit.redo',
  edit_cut: 'menu.edit.cut',
  edit_copy: 'menu.edit.copy',
  edit_paste: 'menu.edit.paste',
  edit_select_all: 'menu.edit.selectAll',
  edit_find_bar: 'menu.edit.find',
  edit_find_find: 'menu.edit.find.find',
  edit_find_prev: 'menu.edit.find.prev',
  edit_find_next: 'menu.edit.find.next',
  edit_find_replace: 'menu.edit.find.replace',
  edit_find_replace_next: 'menu.edit.find.replaceNext',
  edit_find_jump_sel: 'menu.edit.find.jumpSel',
  file_bar: 'menu.file',
  file_new: 'menu.file.new',
  file_new_tab: 'menu.file.newTab',
  file_new_window: 'menu.file.newWindow',
  file_open: 'menu.file.open',
  file_open_file: 'menu.file.openFile',
  file_open_folder: 'menu.file.openFolder',
  file_recent: 'menu.file.recent',
  file_show_intro: 'menu.file.showIntro',
  file_open_location: 'menu.file.openLocation',
  file_delete: 'menu.file.delete',
  file_close: 'menu.file.close',
  file_save: 'menu.file.save',
  file_copy_path: 'menu.file.copyPath',
  file_rename: 'menu.file.rename',
  file_history_bar: 'menu.file.history',
  file_revert: 'menu.file.revert',
  file_save_all: 'menu.file.saveAll',
  file_import: 'menu.file.import',
  file_export_bar: 'menu.file.export',
  file_export_pdf: 'menu.file.export.pdf',
  file_export_html: 'menu.file.export.html',
  file_export_html_plain: 'menu.file.export.htmlPlain',
  file_export_image: 'menu.file.export.image',
  file_export_word: 'menu.file.export.word',
  file_preferences: 'menu.file.preferences',
  file_print: 'menu.file.print',
  fmt_bold: 'menu.fmt.bold',
  fmt_clear: 'menu.fmt.clear',
  fmt_code: 'menu.fmt.code',
  fmt_comment: 'menu.fmt.comment',
  fmt_image_bar: 'menu.fmt.image',
  fmt_image_conv_bar: 'menu.fmt.image.conv',
  fmt_image_conv_html: 'menu.fmt.image.conv.html',
  fmt_image_conv_md: 'menu.fmt.image.conv.md',
  fmt_image_copy_all: 'menu.fmt.image.copyAll',
  fmt_image_copy_to: 'menu.fmt.image.copyTo',
  fmt_image_delete: 'menu.fmt.image.delete',
  fmt_image_global: 'menu.fmt.image.global',
  fmt_image_insert: 'menu.fmt.image.insert',
  fmt_image_insert_local: 'menu.fmt.image.insertLocal',
  fmt_image_move_all: 'menu.fmt.image.moveAll',
  fmt_image_on_insert_bar: 'menu.fmt.image.onInsert',
  fmt_image_on_insert_copy: 'menu.fmt.image.onInsert.copy',
  fmt_image_on_insert_upload: 'menu.fmt.image.onInsert.upload',
  fmt_image_reload_all: 'menu.fmt.image.reloadAll',
  fmt_image_rename: 'menu.fmt.image.rename',
  fmt_image_reveal: 'menu.fmt.image.reveal',
  fmt_image_root: 'menu.fmt.image.root',
  fmt_image_scale: 'menu.fmt.image.scale',
  fmt_image_upload: 'menu.fmt.image.upload',
  fmt_image_upload_all: 'menu.fmt.image.uploadAll',
  fmt_image_zoom_100: 'menu.fmt.image.zoom.100',
  fmt_image_zoom_120: 'menu.fmt.image.zoom.120',
  fmt_image_zoom_150: 'menu.fmt.image.zoom.150',
  fmt_image_zoom_25: 'menu.fmt.image.zoom.25',
  fmt_image_zoom_33: 'menu.fmt.image.zoom.33',
  fmt_image_zoom_50: 'menu.fmt.image.zoom.50',
  fmt_image_zoom_60: 'menu.fmt.image.zoom.60',
  fmt_image_zoom_80: 'menu.fmt.image.zoom.80',
  fmt_inline_math: 'menu.fmt.inlineMath',
  fmt_italic: 'menu.fmt.italic',
  fmt_link: 'menu.fmt.link',
  fmt_link_copy: 'menu.fmt.linkCopy',
  fmt_link_open: 'menu.fmt.linkOpen',
  fmt_link_ops: 'menu.fmt.linkOps',
  fmt_strike: 'menu.fmt.strike',
  fmt_underline: 'menu.fmt.underline',
  view_bar: 'menu.view',
  view_source: 'menu.view.source',
  view_focus: 'menu.view.focus',
  view_sidebar: 'menu.view.sidebar',
  view_outline: 'menu.view.outline',
  view_doc_list: 'menu.view.docList',
  view_search: 'menu.view.search',
  view_word_count: 'menu.view.wordCount',
  view_fullscreen: 'menu.view.fullscreen',
  view_live_preview: 'menu.view.livePreview',
  paragraph: 'menu.paragraph',
  format_menu: 'menu.format',
  window_menu: 'menu.window',
  native_help_bar: 'menu.native.help',
  native_help_about: 'menu.native.help.about',
  native_help_privacy: 'menu.native.help.privacy',
  native_help_website: 'menu.native.help.website',
  native_help_feedback: 'menu.native.help.feedback',
  native_recent_empty: 'menu.native.recentEmpty',
  native_theme: 'menu.native.theme',
  native_theme_open_folder: 'menu.native.themeOpenFolder',
  native_theme_refresh_css: 'menu.native.themeRefreshCss',
  native_app_hide: 'menu.native.app.hide',
  native_app_hide_others: 'menu.native.app.hideOthers',
  native_app_show_all: 'menu.native.app.showAll',
  native_app_quit: 'menu.native.app.quit',
  native_win_close: 'menu.native.win.close',
}

const UI_TO_SHELL = Object.fromEntries(
  Object.entries(SHELL_TO_UI_LABEL_KEY).map(([shell, ui]) => [ui, shell]),
) as Record<string, string>

/** Compile UI `menu.*` keys into shell `menu` section snake_case keys*/
export function uiLabelKeyToShellKey(labelKey: string): string | null {
  return UI_TO_SHELL[labelKey] ?? null
}

/** Resolve shell keys into UI `menu.*` keys*/
export function shellKeyToUiLabelKey(shellKey: string): string | null {
  return SHELL_TO_UI_LABEL_KEY[shellKey] ?? null
}
