import { buildAppMenuSchema } from './commandManifest.build'

/**
 * The top bar menu structure is generated by Command Manifest (`commandManifest.structure.ts` + `commandManifest.entries.ts`).
 * Handwriting label / icon / accelerator is prohibited in this document.
 */
export const APP_MENU_SCHEMA = buildAppMenuSchema()
