// @generated by scripts/export_menu_rust_manifest.py — do not edit

/// Top-bar menu_item action ids (empty when menus are React-only in the webview)
pub const REQUIRED_MENU_ACTION_IDS: &[&str] = &[
];

/// Edit P0: zh-CN runtime contract (shell field name, expected value)
pub const ZH_CN_EDIT_P0_CONTRACT: &[(&str, &str)] = &[
];
