import type { SettingsItem } from './settingsTypes'
import { THEME_CATALOG, type ThemeCatalogGroup } from '../theme-runtime/themeCatalog'
import { EDITOR_FONT_GROUP_KEYS, EDITOR_FONT_PRESETS } from './editorFontPresets'
import { EDITOR_FONT_SIZE_MAX, EDITOR_FONT_SIZE_MIN } from './editorTypography'
import { EDITOR_COLUMN_WIDTH_OPTIONS } from './editorColumnWidth'

const THEME_GROUP_KEYS: Record<ThemeCatalogGroup, string> = {
  GitHub: 'settings.theme.github',
  IDEA: 'settings.theme.idea',
  Dim: 'settings.theme.dim',
}

const THEME_VARIANT_LABEL_KEYS: Record<string, string> = {
  'github-light': 'settings.theme.variant.githubLight',
  'github-dark': 'settings.theme.variant.githubDark',
  'idea-light': 'settings.theme.variant.ideaLight',
  'idea-dark': 'settings.theme.variant.ideaDark',
  'dim-light': 'settings.theme.variant.dimLight',
  'dim-dark': 'settings.theme.variant.dimDark',
}

export const SETTINGS_SCHEMA: readonly SettingsItem[] = [
  {
    type: 'group',
    id: 'general.updates',
    section: 'general',
    titleKey: 'settings.updates.title',
    items: ['updates.autoCheckEnabled'],
  },
  {
    type: 'switch',
    id: 'updates.autoCheckEnabled',
    path: 'updates.autoCheckEnabled',
    section: 'general',
    labelKey: 'settings.updates.autoCheck.label',
    default: true,
  },
  {
    type: 'group',
    id: 'language.general',
    section: 'language',
    titleKey: 'settings.language.title',
    items: ['general.language'],
  },
  {
    type: 'select',
    id: 'general.language',
    path: 'general.language',
    section: 'language',
    labelKey: 'settings.language.language.label',
    options: [],
    default: 'system',
  },
  {
    type: 'group',
    id: 'appearance.builtin',
    section: 'appearance',
    titleKey: 'settings.theme.builtin.title',
    items: ['theme.active', 'theme.customThemeFile'],
  },
  {
    type: 'group',
    id: 'appearance.externalCss',
    section: 'appearance',
    titleKey: 'settings.theme.externalCss.title',
    items: ['theme.cssFile'],
  },
  {
    type: 'group',
    id: 'appearance.snippets',
    section: 'appearance',
    titleKey: 'settings.theme.cssSnippets.sectionTitle',
    items: [],
  },
  {
    type: 'group',
    id: 'export.general',
    section: 'export',
    titleKey: 'settings.export.title',
    items: ['export.preset', 'export.tocMode', 'export.pageBreakMode'],
  },
  {
    type: 'group',
    id: 'export.styles',
    section: 'export',
    titleKey: 'settings.theme.exportCss.sectionTitle',
    items: [],
  },
  {
    type: 'select',
    id: 'theme.active',
    path: 'theme.active',
    section: 'appearance',
    labelKey: 'settings.theme.active.label',
    options: THEME_CATALOG.map((entry) => ({
      labelKey: THEME_VARIANT_LABEL_KEYS[entry.id] ?? entry.id,
      value: entry.id,
      groupKey: THEME_GROUP_KEYS[entry.group],
    })),
    default: 'github-dark',
  },
  {
    type: 'select',
    id: 'theme.cssFile',
    path: 'theme.cssFile',
    section: 'appearance',
    labelKey: 'settings.theme.cssFile.label',
    descriptionKey: 'settings.theme.cssFile.description',
    descriptionAsHelp: true,
    options: [],
    default: '',
  },
  {
    type: 'select',
    id: 'export.preset',
    path: 'export.preset',
    section: 'export',
    labelKey: 'settings.export.preset.label',
    options: [
      { labelKey: 'settings.export.preset.printA4', value: 'print-a4' },
      { labelKey: 'settings.export.preset.compactA4', value: 'compact-a4' },
      { labelKey: 'settings.export.preset.letter', value: 'letter' },
    ],
    default: 'print-a4',
  },
  {
    type: 'select',
    id: 'export.tocMode',
    path: 'export.tocMode',
    section: 'export',
    labelKey: 'settings.export.tocMode.label',
    descriptionKey: 'settings.export.tocMode.description',
    descriptionAsHelp: true,
    options: [
      { labelKey: 'settings.export.tocMode.markerOnly', value: 'marker-only' },
      { labelKey: 'settings.export.tocMode.always', value: 'always' },
      { labelKey: 'settings.export.tocMode.off', value: 'off' },
    ],
    default: 'marker-only',
  },
  {
    type: 'select',
    id: 'export.pageBreakMode',
    path: 'export.pageBreakMode',
    section: 'export',
    labelKey: 'settings.export.pageBreakMode.label',
    descriptionKey: 'settings.export.pageBreakMode.description',
    descriptionAsHelp: true,
    options: [
      { labelKey: 'settings.export.pageBreakMode.avoidBlocks', value: 'avoid-blocks' },
      { labelKey: 'settings.export.pageBreakMode.flow', value: 'flow' },
    ],
    default: 'avoid-blocks',
  },
  {
    type: 'file',
    id: 'theme.customThemeFile',
    path: 'theme.customThemeFile',
    section: 'appearance',
    labelKey: 'settings.theme.customThemeFile.label',
    descriptionKey: 'settings.theme.customThemeFile.description',
    descriptionAsHelp: true,
    accept: '.json,application/json',
    default: '',
    action: {
      id: 'theme.importCustomFile',
      labelKey: 'settings.theme.customThemeFile.import',
      variant: 'secondary',
    },
  },
  {
    type: 'group',
    id: 'editor.typography',
    section: 'editor',
    titleKey: 'settings.editor.groups.typography.title',
    items: ['editor.fontFamily', 'editor.fontSize', 'editor.columnWidth', 'editor.formatToolbarEnabled'],
  },
  {
    type: 'group',
    id: 'editor.autosave',
    section: 'editor',
    titleKey: 'settings.editor.groups.autosave.title',
    items: ['editor.autosaveEnabled', 'editor.autosaveIntervalSec', 'editor.autosaveScope'],
  },
  {
    type: 'group',
    id: 'templates.workspace',
    section: 'templates',
    titleKey: 'settings.templates.groups.workspace.title',
    hideHeader: true,
    items: [],
  },
  {
    type: 'group',
    id: 'import.storage',
    section: 'import',
    titleKey: 'settings.assets.title',
    items: [
      'assets.storage.mode',
      'assets.relative.folderTemplate',
      'assets.absolute.path',
    ],
  },
  {
    type: 'select',
    id: 'assets.storage.mode',
    path: 'assets.storage.mode',
    section: 'import',
    labelKey: 'settings.assets.storageMode.label',
    descriptionKey: 'settings.assets.storageMode.description',
    descriptionAsHelp: true,
    options: [
      {
        labelKey: 'settings.assets.storageMode.relative',
        value: 'relative_to_document',
        descriptionKey: 'settings.assets.storageMode.relative.description',
      },
      {
        labelKey: 'settings.assets.storageMode.absolute',
        value: 'absolute_path',
        descriptionKey: 'settings.assets.storageMode.absolute.description',
      },
    ],
    default: 'relative_to_document',
  },
  {
    type: 'input',
    id: 'assets.relative.folderTemplate',
    path: 'assets.relative.folderTemplate',
    section: 'import',
    labelKey: 'settings.assets.folderTemplate.label',
    descriptionKey: 'settings.assets.folderTemplate.description',
    descriptionAsHelp: true,
    placeholderKey: 'settings.assets.folderTemplate.placeholder',
    helpTextKey: 'settings.assets.folderTemplate.help',
    default: '{doc-name}-assets',
    visibleWhen: {
      path: 'assets.storage.mode',
      equals: 'relative_to_document',
    },
  },
  {
    type: 'input',
    id: 'assets.absolute.path',
    path: 'assets.absolute.path',
    section: 'import',
    labelKey: 'settings.assets.absolutePath.label',
    descriptionKey: 'settings.assets.absolutePath.description',
    descriptionAsHelp: true,
    placeholderKey: 'settings.assets.absolutePath.placeholder',
    default: '',
    action: {
      id: 'assets.pickAbsolutePath',
      labelKey: 'settings.assets.absolutePath.selectFolder',
      variant: 'secondary',
    },
    visibleWhen: {
      path: 'assets.storage.mode',
      equals: 'absolute_path',
    },
  },
  {
    type: 'select',
    id: 'editor.fontFamily',
    path: 'editor.fontFamily',
    section: 'editor',
    labelKey: 'settings.editor.fontFamily.label',
    options: [
      {
        labelKey: 'settings.editor.fontFamily.option.default',
        value: '',
        groupKey: EDITOR_FONT_GROUP_KEYS.general,
      },
      ...EDITOR_FONT_PRESETS.map((preset) => ({
        label: preset.label,
        value: preset.value,
        groupKey: preset.groupKey,
      })),
    ],
    default: '',
  },
  {
    type: 'input',
    id: 'editor.fontSize',
    path: 'editor.fontSize',
    section: 'editor',
    labelKey: 'settings.editor.fontSize.label',
    descriptionKey: 'settings.editor.fontSize.description',
    descriptionAsHelp: true,
    placeholderKey: 'settings.editor.fontSize.placeholder',
    default: '',
    numeric: true,
    min: EDITOR_FONT_SIZE_MIN,
    max: EDITOR_FONT_SIZE_MAX,
  },
  {
    type: 'select',
    id: 'editor.columnWidth',
    path: 'editor.columnWidth',
    section: 'editor',
    labelKey: 'settings.editor.columnWidth.label',
    descriptionKey: 'settings.editor.columnWidth.description',
    descriptionAsHelp: true,
    options: EDITOR_COLUMN_WIDTH_OPTIONS.map((px) => ({
      labelKey: `settings.editor.columnWidth.option.${px}`,
      value: String(px),
    })),
    default: '860',
  },
  {
    type: 'switch',
    id: 'editor.formatToolbarEnabled',
    path: 'editor.formatToolbarEnabled',
    section: 'editor',
    labelKey: 'settings.editor.formatToolbarEnabled.label',
    descriptionKey: 'settings.editor.formatToolbarEnabled.description',
    descriptionAsHelp: true,
    default: true,
  },
  {
    type: 'switch',
    id: 'editor.autosaveEnabled',
    path: 'editor.autosaveEnabled',
    section: 'editor',
    labelKey: 'settings.editor.autosaveEnabled.label',
    default: true,
  },
  {
    type: 'input',
    id: 'editor.autosaveIntervalSec',
    path: 'editor.autosaveIntervalSec',
    section: 'editor',
    labelKey: 'settings.editor.autosaveIntervalSec.label',
    descriptionKey: 'settings.editor.autosaveIntervalSec.description',
    placeholderKey: 'settings.editor.autosaveIntervalSec.placeholder',
    default: '120',
    numeric: true,
    min: 30,
    max: 600,
    visibleWhen: { path: 'editor.autosaveEnabled', equals: true },
  },
  {
    type: 'select',
    id: 'editor.autosaveScope',
    path: 'editor.autosaveScope',
    section: 'editor',
    labelKey: 'settings.editor.autosaveScope.label',
    descriptionKey: 'settings.editor.autosaveScope.description',
    descriptionAsHelp: true,
    options: [
      { labelKey: 'settings.editor.autosaveScope.activeOnly', value: 'activeOnly' },
      { labelKey: 'settings.editor.autosaveScope.allDirty', value: 'allDirty' },
    ],
    default: 'activeOnly',
    visibleWhen: { path: 'editor.autosaveEnabled', equals: true },
  },
]
