import type { SettingsItem } from './settingsTypes'
import { THEME_CATALOG } from '../theme-runtime/themeCatalog'
import { EDITOR_FONT_GROUP_KEYS, EDITOR_FONT_PRESETS } from './editorFontPresets'
import { EDITOR_FONT_SIZE_MAX, EDITOR_FONT_SIZE_MIN } from './editorTypography'

export const SETTINGS_SCHEMA: readonly SettingsItem[] = [
  {
    type: 'group',
    id: 'general.updates',
    section: 'general',
    titleKey: 'settings.updates.title',
    descriptionKey: 'settings.updates.description',
    items: ['updates.autoCheckEnabled'],
  },
  {
    type: 'switch',
    id: 'updates.autoCheckEnabled',
    path: 'updates.autoCheckEnabled',
    section: 'general',
    labelKey: 'settings.updates.autoCheck.label',
    descriptionKey: 'settings.updates.autoCheck.description',
    default: true,
  },
  {
    type: 'group',
    id: 'language.general',
    section: 'language',
    titleKey: 'settings.language.title',
    descriptionKey: 'settings.language.description',
    items: ['general.language'],
  },
  {
    type: 'select',
    id: 'general.language',
    path: 'general.language',
    section: 'language',
    labelKey: 'settings.language.language.label',
    descriptionKey: 'settings.language.language.description',
    options: [],
    default: 'system',
  },
  {
    type: 'group',
    id: 'appearance.builtin',
    section: 'appearance',
    titleKey: 'settings.theme.builtin.title',
    descriptionKey: 'settings.theme.builtin.description',
    items: ['theme.active', 'theme.customThemeFile'],
  },
  {
    type: 'group',
    id: 'appearance.obsidianCss',
    section: 'appearance',
    titleKey: 'settings.theme.obsidianCss.title',
    descriptionKey: 'settings.theme.obsidianCss.description',
    items: ['theme.cssCompatMode', 'theme.cssFile'],
  },
  {
    type: 'group',
    id: 'appearance.snippets',
    section: 'appearance',
    titleKey: 'settings.theme.cssSnippets.sectionTitle',
    descriptionKey: 'settings.theme.cssSnippets.sectionDescription',
    items: [],
  },
  {
    type: 'group',
    id: 'export.general',
    section: 'export',
    titleKey: 'settings.export.title',
    descriptionKey: 'settings.export.description',
    items: ['export.preset', 'export.tocMode', 'export.pageBreakMode'],
  },
  {
    type: 'group',
    id: 'export.styles',
    section: 'export',
    titleKey: 'settings.theme.exportCss.sectionTitle',
    descriptionKey: 'settings.theme.exportCss.sectionDescription',
    items: [],
  },
  {
    type: 'select',
    id: 'theme.active',
    path: 'theme.active',
    section: 'appearance',
    labelKey: 'settings.theme.active.label',
    descriptionKey: 'settings.theme.active.description',
    options: THEME_CATALOG.map((entry) => ({
      label: entry.name,
      value: entry.id,
      group: entry.group,
      description: entry.description,
    })),
    default: 'github-dark',
  },
  {
    type: 'select',
    id: 'theme.cssCompatMode',
    path: 'theme.cssCompatMode',
    section: 'appearance',
    labelKey: 'settings.theme.cssCompatMode.label',
    descriptionKey: 'settings.theme.cssCompatMode.description',
    options: [
      {
        labelKey: 'settings.theme.cssCompatMode.obsidianAuto',
        value: 'obsidian-auto',
      },
      {
        labelKey: 'settings.theme.cssCompatMode.native',
        value: 'native',
      },
    ],
    default: 'obsidian-auto',
  },
  {
    type: 'select',
    id: 'theme.cssFile',
    path: 'theme.cssFile',
    section: 'appearance',
    labelKey: 'settings.theme.cssFile.label',
    descriptionKey: 'settings.theme.cssFile.description',
    options: [],
    default: '',
  },
  {
    type: 'select',
    id: 'export.preset',
    path: 'export.preset',
    section: 'export',
    labelKey: 'settings.export.preset.label',
    descriptionKey: 'settings.export.preset.description',
    options: [
      { labelKey: 'settings.export.preset.printA4', value: 'print-a4' },
      { labelKey: 'settings.export.preset.compactA4', value: 'compact-a4' },
      { labelKey: 'settings.export.preset.letter', value: 'letter' },
    ],
    default: 'print-a4',
  },
  {
    type: 'select',
    id: 'export.tocMode',
    path: 'export.tocMode',
    section: 'export',
    labelKey: 'settings.export.tocMode.label',
    descriptionKey: 'settings.export.tocMode.description',
    options: [
      { labelKey: 'settings.export.tocMode.markerOnly', value: 'marker-only' },
      { labelKey: 'settings.export.tocMode.always', value: 'always' },
      { labelKey: 'settings.export.tocMode.off', value: 'off' },
    ],
    default: 'marker-only',
  },
  {
    type: 'select',
    id: 'export.pageBreakMode',
    path: 'export.pageBreakMode',
    section: 'export',
    labelKey: 'settings.export.pageBreakMode.label',
    descriptionKey: 'settings.export.pageBreakMode.description',
    options: [
      { labelKey: 'settings.export.pageBreakMode.avoidBlocks', value: 'avoid-blocks' },
      { labelKey: 'settings.export.pageBreakMode.flow', value: 'flow' },
    ],
    default: 'avoid-blocks',
  },
  {
    type: 'file',
    id: 'theme.customThemeFile',
    path: 'theme.customThemeFile',
    section: 'appearance',
    labelKey: 'settings.theme.customThemeFile.label',
    descriptionKey: 'settings.theme.customThemeFile.description',
    accept: '.json,application/json',
    default: '',
    action: {
      id: 'theme.importCustomFile',
      labelKey: 'settings.theme.customThemeFile.import',
      variant: 'secondary',
    },
  },
  {
    type: 'group',
    id: 'editor.assets',
    section: 'editor',
    titleKey: 'settings.assets.title',
    descriptionKey: 'settings.assets.description',
    items: [
      'assets.storage.mode',
      'assets.relative.folderTemplate',
      'assets.absolute.path',
    ],
  },
  {
    type: 'select',
    id: 'assets.storage.mode',
    path: 'assets.storage.mode',
    section: 'editor',
    labelKey: 'settings.assets.storageMode.label',
    descriptionKey: 'settings.assets.storageMode.description',
    options: [
      {
        labelKey: 'settings.assets.storageMode.relative',
        value: 'relative_to_document',
        descriptionKey: 'settings.assets.storageMode.relative.description',
      },
      {
        labelKey: 'settings.assets.storageMode.absolute',
        value: 'absolute_path',
        descriptionKey: 'settings.assets.storageMode.absolute.description',
      },
    ],
    default: 'relative_to_document',
  },
  {
    type: 'input',
    id: 'assets.relative.folderTemplate',
    path: 'assets.relative.folderTemplate',
    section: 'editor',
    labelKey: 'settings.assets.folderTemplate.label',
    descriptionKey: 'settings.assets.folderTemplate.description',
    placeholderKey: 'settings.assets.folderTemplate.placeholder',
    helpTextKey: 'settings.assets.folderTemplate.help',
    default: '{doc-name}-assets',
    visibleWhen: {
      path: 'assets.storage.mode',
      equals: 'relative_to_document',
    },
  },
  {
    type: 'input',
    id: 'assets.absolute.path',
    path: 'assets.absolute.path',
    section: 'editor',
    labelKey: 'settings.assets.absolutePath.label',
    descriptionKey: 'settings.assets.absolutePath.description',
    placeholderKey: 'settings.assets.absolutePath.placeholder',
    default: '',
    action: {
      id: 'assets.pickAbsolutePath',
      labelKey: 'settings.assets.absolutePath.selectFolder',
      variant: 'secondary',
    },
    visibleWhen: {
      path: 'assets.storage.mode',
      equals: 'absolute_path',
    },
  },
  {
    type: 'group',
    id: 'editor.general',
    section: 'editor',
    titleKey: 'settings.editor.title',
    descriptionKey: 'settings.editor.description',
    items: [
      'editor.fontFamily',
      'editor.fontSize',
      'editor.autosaveEnabled',
      'editor.autosaveIntervalSec',
      'editor.autosaveScope',
    ],
  },
  {
    type: 'select',
    id: 'editor.fontFamily',
    path: 'editor.fontFamily',
    section: 'editor',
    labelKey: 'settings.editor.fontFamily.label',
    descriptionKey: 'settings.editor.fontFamily.description',
    options: [
      {
        labelKey: 'settings.editor.fontFamily.option.default',
        value: '',
        groupKey: EDITOR_FONT_GROUP_KEYS.general,
      },
      ...EDITOR_FONT_PRESETS.map((preset) => ({
        label: preset.label,
        value: preset.value,
        groupKey: preset.groupKey,
      })),
    ],
    default: '',
  },
  {
    type: 'input',
    id: 'editor.fontSize',
    path: 'editor.fontSize',
    section: 'editor',
    labelKey: 'settings.editor.fontSize.label',
    descriptionKey: 'settings.editor.fontSize.description',
    placeholderKey: 'settings.editor.fontSize.placeholder',
    default: '',
    numeric: true,
    min: EDITOR_FONT_SIZE_MIN,
    max: EDITOR_FONT_SIZE_MAX,
  },
  {
    type: 'switch',
    id: 'editor.autosaveEnabled',
    path: 'editor.autosaveEnabled',
    section: 'editor',
    labelKey: 'settings.editor.autosaveEnabled.label',
    descriptionKey: 'settings.editor.autosaveEnabled.description',
    default: true,
  },
  {
    type: 'input',
    id: 'editor.autosaveIntervalSec',
    path: 'editor.autosaveIntervalSec',
    section: 'editor',
    labelKey: 'settings.editor.autosaveIntervalSec.label',
    descriptionKey: 'settings.editor.autosaveIntervalSec.description',
    placeholderKey: 'settings.editor.autosaveIntervalSec.placeholder',
    default: '120',
    numeric: true,
    min: 30,
    max: 600,
  },
  {
    type: 'select',
    id: 'editor.autosaveScope',
    path: 'editor.autosaveScope',
    section: 'editor',
    labelKey: 'settings.editor.autosaveScope.label',
    descriptionKey: 'settings.editor.autosaveScope.description',
    options: [
      { labelKey: 'settings.editor.autosaveScope.activeOnly', value: 'activeOnly' },
      { labelKey: 'settings.editor.autosaveScope.allDirty', value: 'allDirty' },
    ],
    default: 'activeOnly',
  },
]
